language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 2.0.3
    - os: osx
      osx_image: xcode8.3
      dotnet: 2.0.3

before_script:
  - if test "$TRAVIS_OS_NAME" == "osx"; then export FrameworkPathOverride=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/; else export FrameworkPathOverride=/usr/lib/mono/4.5/; fi

script:
  - git fetch --unshallow --tags
  - git remote -v show origin
  - ./build.sh --linksources=true --verbosity=verbose
