language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: none
      dotnet: 1.0.0-preview2-003121
    - os: osx
      osx_image: xcode7.2
      mono: none
      dotnet: 1.0.0-preview2-003121

script:
  - dotnet --info
  - ./build.sh UnitTestsDotNetCore