name: Add PRs and issues to Octokit org project

on:
  issues:
    types: [reopened, opened]
  pull_request:
    types: [reopened, opened]
    
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@latest
        with:
          project-url: https://github.com/orgs/octokit/projects/10
          github-token: ${{ secrets.OCTOKITBOT_PAT }}
          labeled: 'Status: Stale'
          label-operator: NOT
